1:1.hpp
	g++ 1.hpp -std=c++11 -o 1
1-test:1-test.cpp
	g++ 1-test.cpp -std=c++11 -o 1-test

449:449.hpp
	g++ 449.hpp -std=c++11 -o 449
449-test:449-test.cpp
	g++ 449-test.cpp -std=c++11 -o 449-test

812:812.hpp
	g++ 812.hpp -std=c++11 -o 812
812-test:812-test.cpp
	g++ 812-test.cpp -std=c++11 -o 812-test

895:895.hpp
	g++ 895.hpp -std=c++11 -o 895
895-test:895-test.cpp
	g++ 895-test.cpp -std=c++11 -o 895-test

944:944.hpp
	g++ 944.hpp -std=c++11 -o 944
944-test:944-test.cpp
	g++ 944-test.cpp -std=c++11 -o 944-test

01_05:01_05.hpp
	g++ 01_05.hpp -std=c++11 -o 01_05
01_05-test:01_05-test.cpp
	g++ 01_05-test.cpp -std=c++11 -o 01_05-test


04_06:04_06.hpp
	g++ 04_06.hpp -std=c++11 -o 04_06
04_06-test:04_06-test.cpp
	g++ 04_06-test.cpp -std=c++11 -o 04_06-test

953:953.hpp
	g++ 953.hpp -std=c++11 -o 953
953-test:953-test.cpp
	g++ 953-test.cpp -std=c++11 -o 953-test

668:668.hpp
	g++ 668.hpp -std=c++11 -o 668
668-test:668-test.cpp
	g++ 668-test.cpp -std=c++11 -o 668-test

462:462.hpp
	g++ 462.hpp -std=c++11 -o 462
462-test:462-test.cpp
	g++ 462-test.cpp -std=c++11 -o 462-test

clean:
	rm -rf `ls | grep [^pp]$$`
