name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: |
        cd ${{ github.workspace }}/code
        make all
    - name: test
      run: |
        cd ${{ github.workspace }}/code
        make test
    - name: Comment
      uses: thollander/actions-comment-pull-request@v1.4.1
        with:
        message: |
          Hello $(make test) 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}






                    