name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: |
        cd ${{ github.workspace }}/code
        make all
    - name: test
      run: |
        cd ${{ github.workspace }}/code
        echo "::set-output name=test_result::$(make test)"
    - name: comment
      uses: NejcZdovc/comment-pr@v1.1.1
      with:
        message: "`${{ steps.test.outputs.test_result }}`"
        github_token: ${{secrets.GITHUB_TOKEN}}

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ${{ github.workspace }}/code/.*-test$






                    