name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: |
        cd ${{ github.workspace }}/code
        make all
    - name: test
      run: |
        cd ${{ github.workspace }}/code
        make test
    - name: Comment
      uses: JoseThen/comment-pr@v1.1.1
      with:
        comment: $(make test)
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          




                    